require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

module Seo
  describe MetaContentsController do
    routes { Engine.routes }
  
    # This should return the minimal set of attributes required to create a valid
    # MetaContent. As you add validations to MetaContent, be sure to
    # adjust the attributes here as well.
    let(:valid_attributes) { {
        resource_id: "1",
        resource_type: "Project",
        meta_title: "The only project",
        meta_description: "worth reading its tests for",
        meta_keywords: "project, keywords"
      } }
  
    # This should return the minimal set of values that should be in the session
    # in order to pass any filters (e.g. authentication) defined in
    # MetaContentsController. Be sure to keep this updated too.
    let(:valid_session) { {} }
  
    describe "GET index" do
      it "assigns all meta_contents as @meta_contents" do
        meta_content = MetaContent.create! valid_attributes
        get :index, {}, valid_session
        assigns(:meta_contents).should eq([meta_content])
      end
    end
  
    describe "GET show" do
      it "assigns the requested meta_content as @meta_content" do
        meta_content = MetaContent.create! valid_attributes
        get :show, {:id => meta_content.to_param}, valid_session
        assigns(:meta_content).should eq(meta_content)
      end
    end
  
    describe "GET new" do
      it "assigns a new meta_content as @meta_content" do
        get :new, {}, valid_session
        assigns(:meta_content).should be_a_new(MetaContent)
      end
    end
  
    describe "GET edit" do
      it "assigns the requested meta_content as @meta_content" do
        meta_content = MetaContent.create! valid_attributes
        get :edit, {:id => meta_content.to_param}, valid_session
        assigns(:meta_content).should eq(meta_content)
      end
    end
  
    describe "POST create" do
      describe "with valid params" do
        it "creates a new MetaContent" do
          expect {
            post :create, {:meta_content => valid_attributes}, valid_session
          }.to change(MetaContent, :count).by(1)
        end
  
        it "assigns a newly created meta_content as @meta_content" do
          post :create, {:meta_content => valid_attributes}, valid_session
          assigns(:meta_content).should be_a(MetaContent)
          assigns(:meta_content).should be_persisted
        end
  
        it "redirects to the created meta_content" do
          post :create, {:meta_content => valid_attributes}, valid_session
          response.should redirect_to(MetaContent.last)
        end
      end
  
      describe "with invalid params" do
        it "assigns a newly created but unsaved meta_content as @meta_content" do
          # Trigger the behavior that occurs when invalid params are submitted
          MetaContent.any_instance.stub(:save).and_return(false)
          post :create, {:meta_content => { "resource_id" => "invalid value" }}, valid_session
          assigns(:meta_content).should be_a_new(MetaContent)
        end
  
        it "re-renders the 'new' template" do
          # Trigger the behavior that occurs when invalid params are submitted
          MetaContent.any_instance.stub(:save).and_return(false)
          post :create, {:meta_content => { "resource_id" => "invalid value" }}, valid_session
          response.should render_template("new")
        end
      end
    end
  
    describe "PUT update" do
      describe "with valid params" do
        it "updates the requested meta_content" do
          meta_content = MetaContent.create! valid_attributes
          # Assuming there are no other meta_contents in the database, this
          # specifies that the MetaContent created on the previous line
          # receives the :update_attributes message with whatever params are
          # submitted in the request.
          MetaContent.any_instance.should_receive(:update_attributes).with({ "resource_id" => "1" })
          put :update, {:id => meta_content.to_param, :meta_content => { "resource_id" => "1" }}, valid_session
        end
  
        it "assigns the requested meta_content as @meta_content" do
          meta_content = MetaContent.create! valid_attributes
          put :update, {:id => meta_content.to_param, :meta_content => valid_attributes}, valid_session
          assigns(:meta_content).should eq(meta_content)
        end
  
        it "redirects to the meta_content" do
          meta_content = MetaContent.create! valid_attributes
          put :update, {:id => meta_content.to_param, :meta_content => valid_attributes}, valid_session
          response.should redirect_to(meta_content)
        end
      end
  
      describe "with invalid params" do
        it "assigns the meta_content as @meta_content" do
          meta_content = MetaContent.create! valid_attributes
          # Trigger the behavior that occurs when invalid params are submitted
          MetaContent.any_instance.stub(:save).and_return(false)
          put :update, {:id => meta_content.to_param, :meta_content => { "resource_id" => "invalid value" }}, valid_session
          assigns(:meta_content).should eq(meta_content)
        end
  
        it "re-renders the 'edit' template" do
          meta_content = MetaContent.create! valid_attributes
          # Trigger the behavior that occurs when invalid params are submitted
          MetaContent.any_instance.stub(:save).and_return(false)
          put :update, {:id => meta_content.to_param, :meta_content => { "resource_id" => "invalid value" }}, valid_session
          response.should render_template("edit")
        end
      end
    end
  
    describe "DELETE destroy" do
      it "destroys the requested meta_content" do
        meta_content = MetaContent.create! valid_attributes
        expect {
          delete :destroy, {:id => meta_content.to_param}, valid_session
        }.to change(MetaContent, :count).by(-1)
      end
  
      it "redirects to the meta_contents list" do
        meta_content = MetaContent.create! valid_attributes
        delete :destroy, {:id => meta_content.to_param}, valid_session
        response.should redirect_to(meta_contents_url)
      end
    end
  
  end
end
